resilience4j:
  timelimiter:
    instances:
      aviationService:
        timeoutDuration: 10ms
  circuitbreaker:
    instances:
      aviationService:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      aviationService:
        maxAttempts: 3
        waitDuration: 2s
logging:
  level:
    com.opennet.assignment.aviation.client.AviationClient: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

aviation:
  api:
    url: https://api.aviationapi.com/v1